### ISSUE TITLE
Please add license information

### ISSUE THREAD

**Issue by bdrung** [wtarreau/mhz#2]
Please add license information. Otherwise this software is considered non-free.

**Comment by robimarko** [comment]
Hi,
I regularly use this tool for clock driver validation, so adding a license would allow me to package it into Buildroot and OpenWrt as I really find the tool useful.

Regards,
Robert

**Comment by wtarreau** [comment]
Sorry for the delay, I don't receive github notifications. I've added an MIT license now.

**Comment by robimarko** [comment]
Thanks for this.

**Comment by wtarreau** [comment]
You're welcome. I've also added options to show the usage (-h), show only cpu (-c) or only tsc (-t) freq (saves you from having to cut fields) and to report the values as integers (-i) for use in shell scripts. If you want to trim it to its minimum for OpenWRT, we can easily get rid of the TSC stuff and maybe even just show the cpu-only output in integer mode.

**Comment by robimarko** [comment]
Yeah, I saw that and that is great as well.
There is no need to trim it for OpenWrt as its an optional tool, I already made a PR for it as it has been an awesome tool for testing CPUFreq additions.

**Comment by wtarreau** [comment]
I definitely agree :-)
